### ISSUE TITLE
'c' символ заменяется не корректно

### ISSUE THREAD

**Issue by innagorda** [shramko/mssql#1]
Взяла код процедуры, нужно было применить для переименования названий полей таблицы, т.к. в системе, в которой буду использовать, есть ограничение на кодировку. В итоге получилась неприятная штука - 'c' символы заменились на �. 'c' - русская, а все остальное корректно. Конечно, это ерунда, вылечилось заменой. Просто подправьте у себя, чтобы было без ошибок.
Спасибо за полезную процедуру.

**Comment by shramko** [comment]
innagorda, спасибо за комментарий. Поправил в коммите от 21.10.17
